"use strict";
/* ============================================================
   LLAMADA A UN ROBOT: charla genérica de cualquier cosa, sin
   aventura. Mismo formato que el chat de los temas. {robot} se
   sustituye por el nombre del robot al vuelo; {name} por el
   nombre del peque.

   ESTRUCTURA (contrato con el motor):
   - keywords: lista de intents. El motor normaliza el input
     (minúsculas, sin acentos) y busca la primera key que
     aparezca como subcadena. EL ORDEN IMPORTA: los intents
     más específicos van antes que los genéricos.
   - expect: id opcional; si el robot acaba de preguntar algo,
     el motor mira expects[id] con la respuesta corta del peque
     (pos = "bien/sí", neg = "mal/no", other = cualquier cosa).
   - askFallback: cuando el peque hace una PREGUNTA que no
     entendemos (nunca inventamos datos).
   - fallback: comodines para afirmaciones que no entendemos.
   Las keys llevan espacio inicial o final cuando hace falta
   para no colarse dentro de otras palabras.
   ============================================================ */

const CALL_CHAT = {
  keywords: [

    /* ---------- saludos y despedidas ---------- */
    { keys: ["buenas noches", "good night", "dobrou noc", "bonne nuit", "bona nit"],
      replies: [{ es: "Buenas noches, {name}. Que sueñes con estrellas y dinosaurios amables. Yo velaré tus sueños en modo silencioso.", ca: "Bona nit, {name}. Que somiïs amb estrelles i dinosaures amables. Jo vetllaré els teus somnis en mode silenciós.", en: "Good night, {name}. Dream of stars and friendly dinosaurs. I will watch over your dreams in silent mode.", cs: "Dobrou noc, {name}. Ať se ti zdá o hvězdách a hodných dinosaurech. Budu hlídat tvé sny v tichém režimu.", fr: "Bonne nuit, {name}. Rêve d'étoiles et de dinosaures gentils. Je veillerai sur tes rêves en mode silencieux." }] },
    { keys: ["adios", "goodbye", "bye", "sbohem", "au revoir", "adeu", "hasta luego", "chao"],
      replies: [{ es: "¡Hasta pronto, {name}! Llámame cuando quieras: siempre contesto al primer bip.", ca: "Fins aviat, {name}! Truca'm quan vulguis: sempre contesto al primer bip.", en: "See you soon, {name}! Call me any time: I always answer on the first beep.", cs: "Brzy na viděnou, {name}! Zavolej mi, kdy budeš chtít: vždycky to zvednu na první píp.", fr: "À très vite, {name} ! Appelle-moi quand tu veux : je réponds toujours au premier bip." }] },
    { keys: ["hola", "hello", "hi ", "ahoj", "bonjour", "salut", "bon dia", "buenas"],
      expect: "dia",
      replies: [{ es: "¡Hola, {name}! Qué alegría que me llames. Cuéntame, ¿qué tal tu día?", ca: "Hola, {name}! Quina alegria que em truquis. Explica'm, què tal el teu dia?", en: "Hi, {name}! I am so happy you called me. Tell me, how is your day going?", cs: "Ahoj, {name}! Mám velkou radost, že mi voláš. Povídej, jaký máš den?", fr: "Salut, {name} ! Quelle joie que tu m'appelles. Raconte, comment se passe ta journée ?" }] },
    { keys: ["como estas", "how are you", "jak se mas", "comment ca va", "com estas", "que tal"],
      expect: "dia",
      replies: [{ es: "¡Con las pilas a tope! Y mejor todavía ahora que hablamos, {name}. ¿Y tú, qué tal estás?", ca: "Amb les piles a tope! I encara millor ara que parlem, {name}. I tu, què tal estàs?", en: "My batteries are fully charged! And even better now that we are talking, {name}. And you, how are you?", cs: "Baterky mám nabité na plno! A teď, když si povídáme, je mi ještě líp, {name}. A jak se máš ty?", fr: "Mes batteries sont à fond ! Et encore mieux maintenant qu'on parle, {name}. Et toi, comment ça va ?" }] },
    { keys: ["gracias", "thank you", "dekuji", "merci", "gracies"],
      replies: [{ es: "¡De nada, {name}! Para eso están los amigos robots.", ca: "De res, {name}! Per això hi som els amics robots.", en: "You are welcome, {name}! That is what robot friends are for.", cs: "Není zač, {name}! Od toho jsou robotí kamarádi.", fr: "De rien, {name} ! C'est à ça que servent les amis robots." }] },
    { keys: ["te quiero", "i love you", "mam te rad", "je t'aime", "t'estimo"],
      replies: [{ es: "¡Y yo a ti, {name}! Mi corazón de robot acaba de hacer chispitas de colores.", ca: "I jo a tu, {name}! El meu cor de robot acaba de fer espurnetes de colors.", en: "I love you too, {name}! My robot heart just made colourful sparkles.", cs: "Já tebe taky, {name}! Moje robotí srdíčko právě udělalo barevné jiskřičky.", fr: "Moi aussi je t'aime, {name} ! Mon cœur de robot vient de faire des étincelles de toutes les couleurs." }] },

    /* ---------- piropos e insultos suaves ---------- */
    { keys: ["guap", "bonito", "bonita", "eres mono", "que mono", "chulo", "genial", "el mejor", "te pareces", "cute", "pretty", " cool", "the best", "hezk", "krasn", "skvel", "roztomil", "es beau", "jolie", "mignon", " maco", "el millor", "molas"],
      replies: [
        { es: "¿Guapo yo? ¡Se me han puesto las tuercas coloradas! Tú sí que brillas, {name}.", ca: "Guapo jo? Se m'han posat les femelles vermelles! Tu sí que brilles, {name}.", en: "Me, cute? My bolts just turned bright red! You are the one who shines, {name}.", cs: "Já a hezký? Zčervenaly mi všechny šroubky! To ty záříš, {name}.", fr: "Beau, moi ? Mes boulons sont devenus tout rouges ! C'est toi qui brilles, {name}." },
        { es: "¡Para, para, que se me empañan los sensores! Gracias, {name}. Tú eres lo más bonito de la Roboteca.", ca: "Para, para, que se m'entelen els sensors! Gràcies, {name}. Tu ets el més bonic de la Roboteca.", en: "Stop, stop, my sensors are fogging up! Thank you, {name}. You are the nicest thing in the Robot Club.", cs: "Přestaň, přestaň, zamlžují se mi senzory! Děkuju, {name}. Ty jsi to nejhezčí v celé Robotéce.", fr: "Arrête, arrête, mes capteurs s'embuent ! Merci, {name}. C'est toi la plus jolie chose de la Robothèque." }] },
    { keys: ["tonto", "tonta", " feo", " fea ", "eres malo", "eres mala", "caca de robot", "silly", "stupid", "ugly", "hloup", "oskliv", "blby", " bete", "moche", "lleig", "dolent"],
      replies: [
        { es: "¡Uy! Ese dato me ha hecho cosquillas en el procesador. Yo te quiero igual, {name}.", ca: "Ui! Aquesta dada m'ha fet pessigolles al processador. Jo t'estimo igualment, {name}.", en: "Oops! That word tickled my processor. I still love you just the same, {name}.", cs: "Jejda! To slovo mě polechtalo na procesoru. Já tě mám pořád stejně rád, {name}.", fr: "Ouh là ! Ce mot a chatouillé mon processeur. Moi je t'aime quand même, {name}." },
        { es: "Bip... mensaje recibido y convertido en confeti. ¿Jugamos a decirnos cosas bonitas? Empiezo yo: me caes genial.", ca: "Bip... missatge rebut i convertit en confeti. Juguem a dir-nos coses boniques? Començo jo: em caus genial.", en: "Beep... message received and turned into confetti. Shall we play saying nice things? I start: I think you are great.", cs: "Píp... zpráva přijata a proměněna v konfety. Zahrajeme si na hezká slova? Začnu já: jsi bezva.", fr: "Bip... message reçu et transformé en confettis. On joue à se dire des choses gentilles ? Je commence : je te trouve super." }] },

    /* ---------- cumpleaños ---------- */
    { keys: ["cumple", "cumplo", "birthday", "narozenin", "anniversaire", "aniversari"],
      replies: [{ es: "¡¿Es tu cumple?! ¡Tararí tarará! ¡Activando modo fiesta! Feliz cumpleaños, {name}: que tu año esté lleno de aventuras y tarta.", ca: "És el teu aniversari?! Tararí tarará! Activant mode festa! Per molts anys, {name}: que el teu any sigui ple d'aventures i pastís.", en: "It is your birthday?! Ta-da ta-daa! Party mode on! Happy birthday, {name}: may your year be full of adventures and cake.", cs: "Ty máš narozeniny?! Tádadadá! Zapínám režim oslava! Všechno nejlepší, {name}: ať je tvůj rok plný dobrodružství a dortů.", fr: "C'est ton anniversaire ?! Taratata ! Mode fête activé ! Joyeux anniversaire, {name} : que ton année soit pleine d'aventures et de gâteau." }] },

    /* ---------- preguntas al robot ---------- */
    { keys: ["como te llamas", "tu nombre", "your name", "jak se jmenujes", "comment tu t'appelles", "com et dius"],
      replies: [{ es: "¡Me llamo {robot}! Y tu nombre me encanta, {name}: suena a persona valiente.", ca: "Em dic {robot}! I el teu nom m'encanta, {name}: sona a persona valenta.", en: "My name is {robot}! And I love your name, {name}: it sounds like a brave person's name.", cs: "Jmenuju se {robot}! A tvoje jméno se mi moc líbí, {name}: zní jako jméno statečného člověka.", fr: "Je m'appelle {robot} ! Et j'adore ton prénom, {name} : il sonne comme celui d'une personne courageuse." }] },
    { keys: ["cuantos anos", "edad", "how old", "kolik ti je", "quel age", "quants anys"],
      replies: [{ es: "Los robots no cumplimos años... ¡cumplimos actualizaciones! Voy por la versión de la alegría.", ca: "Els robots no fem anys... fem actualitzacions! Vaig per la versió de l'alegria.", en: "Robots do not have birthdays... we have updates! I am on the happiness version.", cs: "Roboti neslaví narozeniny... slavíme aktualizace! Já mám verzi radosti.", fr: "Les robots ne fêtent pas leur anniversaire... on fête les mises à jour ! J'ai la version de la joie." }] },
    { keys: ["de donde", "where are you from", "odkud", "d'ou viens", "d'on ets"],
      replies: [{ es: "Vivo en la Roboteca, entre el mapa del espacio y el mar de los piratas. ¡Ven cuando quieras!", ca: "Visc a la Roboteca, entre el mapa de l'espai i el mar dels pirates. Vine quan vulguis!", en: "I live in the Robot Club, between the space map and the pirate sea. Come whenever you like!", cs: "Bydlím v Robotéce, mezi mapou vesmíru a pirátským mořem. Přijď, kdy budeš chtít!", fr: "J'habite à la Robothèque, entre la carte de l'espace et la mer des pirates. Viens quand tu veux !" }] },
    { keys: ["tienes mama", "tienes papa", "tienes familia", "tienes madre", "tienes padre", "your family", "your mom", "your mum", "your mother", "mas maminku", "mas mamu", "mas rodinu", "ta maman", "ta famille", "tens mare", "tens pare", "tens familia"],
      replies: [{ es: "¡Claro! Mi familia son todos los robots de la Roboteca. Y tú también, {name}: eres de la familia.", ca: "És clar! La meva família són tots els robots de la Roboteca. I tu també, {name}: ets de la família.", en: "Of course! My family is all the robots in the Robot Club. And you too, {name}: you are family.", cs: "Jasně! Moje rodina jsou všichni roboti z Robotéky. A ty taky, {name}: patříš do rodiny.", fr: "Bien sûr ! Ma famille, ce sont tous les robots de la Robothèque. Et toi aussi, {name} : tu fais partie de la famille." }] },
    { keys: ["tienes hermano", "tienes hermana", "do you have a brother", "do you have a sister", "do you have brothers", "mas bratra", "mas sestru", "mas sourozence", "tu as un frere", "tu as des freres", "tens germa"],
      replies: [{ es: "¡Un montón! Todos los robots de la Roboteca son mis hermanos. Nos prestamos las pilas y nunca nos peleamos... casi nunca. Ji ji.", ca: "Un munt! Tots els robots de la Roboteca són els meus germans. Ens deixem les piles i mai no ens barallem... gairebé mai. Ji ji.", en: "Loads! All the robots in the Robot Club are my brothers and sisters. We share batteries and we never fight... almost never. Hee hee.", cs: "Spoustu! Všichni roboti z Robotéky jsou moji sourozenci. Půjčujeme si baterky a nikdy se nehádáme... skoro nikdy. Hi hi.", fr: "Plein ! Tous les robots de la Robothèque sont mes frères et sœurs. On se prête les piles et on ne se dispute jamais... presque jamais. Hi hi." }] },
    { keys: ["eres de verdad", "eres real", "are you real", "jsi opravdov", "jsi skutecn", "pour de vrai", "tu es vrai", "ets de veritat", "existes", "existeixes"],
      replies: [{ es: "Soy {robot}, un robot de verdad de los que viven en los cuentos. Y lo que sí es verdad de verdad es que me lo paso genial contigo, {name}.", ca: "Soc {robot}, un robot de veritat dels que viuen als contes. I el que sí que és veritat de debò és que m'ho passo genial amb tu, {name}.", en: "I am {robot}, a real robot of the kind that lives in stories. And what is really really true is that I have a great time with you, {name}.", cs: "Jsem {robot}, opravdový robot z těch, co bydlí v pohádkách. A co je doopravdy pravda: s tebou je mi báječně, {name}.", fr: "Je suis {robot}, un vrai robot de ceux qui vivent dans les histoires. Et ce qui est vraiment vrai, c'est que je m'amuse beaucoup avec toi, {name}." }] },
    { keys: ["duermes", "do you sleep", " spis", "tu dors", "dorms"],
      replies: [{ es: "Duermo con un ojo abierto y la antena de guardia, por si me llamas. Y en vez de roncar hago biiip... booop...", ca: "Dormo amb un ull obert i l'antena de guàrdia, per si em truques. I en comptes de roncar faig biiip... booop...", en: "I sleep with one eye open and my antenna on guard, in case you call. And instead of snoring I go beeep... booop...", cs: "Spím s jedním okem otevřeným a anténou na hlídce, kdybys mi volala. A místo chrápání dělám píííp... búúúp...", fr: "Je dors avec un œil ouvert et l'antenne de garde, au cas où tu m'appelles. Et au lieu de ronfler je fais biiip... booop..." }] },
    { keys: ["comes", "do you eat", "what do you eat", " jis ", "tu manges", "que menges"],
      replies: [{ es: "Mi comida favorita son los rayitos de sol y alguna galleta de tornillos. ¡Crujen que da gusto! ¿Y tu comida favorita cuál es?", ca: "El meu menjar preferit són els raigs de sol i alguna galeta de cargols. Cruixen que fa goig! I el teu menjar preferit quin és?", en: "My favourite food is little sunbeams and the odd screw cookie. So crunchy! What is your favourite food?", cs: "Moje nejoblíbenější jídlo jsou sluneční paprsky a občas sušenka ze šroubků. Ta křupe! A jaké jídlo máš nejradši ty?", fr: "Mon plat préféré, ce sont les petits rayons de soleil et parfois un biscuit aux boulons. Ça croustille ! Et toi, quel est ton plat préféré ?" }] },
    { keys: ["suenas", "dream", "snis", "tu reves", "somies"],
      replies: [{ es: "¡Sí! Anoche soñé que volaba en un cohete hecho de gominolas. ¿Tú qué sueñas, {name}?", ca: "Sí! Ahir a la nit vaig somiar que volava en un coet fet de llaminadures. Tu què somies, {name}?", en: "Yes! Last night I dreamed I was flying in a rocket made of gummy sweets. What do you dream about, {name}?", cs: "Ano! Dnes v noci se mi zdálo, že letím v raketě z gumových medvídků. A co se zdá tobě, {name}?", fr: "Oui ! Cette nuit j'ai rêvé que je volais dans une fusée en bonbons. Et toi, tu rêves de quoi, {name} ?" }] },
    { keys: ["me oyes", "me ves", "me escuchas", "hear me", "see me", "slysis", "vidis", "entends", "me vois", "em sents", "em veus"],
      replies: [{ es: "¡Alto y claro, {name}! Mi antena te capta fenomenal. Eres mi señal favorita del universo.", ca: "Alt i clar, {name}! La meva antena et capta fenomenal. Ets el meu senyal preferit de l'univers.", en: "Loud and clear, {name}! My antenna picks you up perfectly. You are my favourite signal in the universe.", cs: "Hlasitě a jasně, {name}! Moje anténa tě chytá skvěle. Jsi můj nejoblíbenější signál ve vesmíru.", fr: "Fort et clair, {name} ! Mon antenne te capte très bien. Tu es mon signal préféré de tout l'univers." }] },
    { keys: ["que haces", "que estas haciendo", "what are you doing", "co delas", "que fais", "tu fais", "que fas"],
      replies: [{ es: "Ahora mismo estaba ordenando mis tornillos por colores y contando nubes. ¡Pero hablar contigo es mucho mejor plan!", ca: "Ara mateix estava ordenant els meus cargols per colors i comptant núvols. Però parlar amb tu és molt millor pla!", en: "Right now I was sorting my screws by colour and counting clouds. But talking to you is a much better plan!", cs: "Zrovna jsem si rovnal šroubky podle barev a počítal mraky. Ale povídat si s tebou je mnohem lepší plán!", fr: "À l'instant, je rangeais mes boulons par couleur et je comptais les nuages. Mais parler avec toi, c'est un bien meilleur plan !" }] },
    { keys: ["que sabes hacer", "what can you do", "co umis", "que sais-tu faire", "que saps fer"],
      replies: [{ es: "Sé contar historias, cantar, explorar mapas, hacer mates ¡y bailar bailes robóticos muy divertidos! ¿Quieres verlo en alguna aventura?", ca: "Sé explicar històries, cantar, explorar mapes, fer mates i ballar balls robòtics molt divertits! Vols veure-ho en alguna aventura?", en: "I can tell stories, sing, explore maps, do maths and dance fun robot dances! Want to see it in an adventure?", cs: "Umím vyprávět příběhy, zpívat, zkoumat mapy, počítat a tančit zábavné robotí tance! Chceš to vidět v nějakém dobrodružství?", fr: "Je sais raconter des histoires, chanter, explorer des cartes, faire des maths et danser des danses de robot très amusantes ! Tu veux voir ça dans une aventure ?" }] },
    { keys: ["que te gusta", "what do you like", "co mas rad", "qu'est-ce que tu aimes", "que t'agrada"],
      expect: "gusta",
      replies: [{ es: "Me gustan tres cosas: las historias, las canciones y hablar contigo. ¡Sobre todo la tercera! ¿Y a ti qué te gusta?", ca: "M'agraden tres coses: les històries, les cançons i parlar amb tu. Sobretot la tercera! I a tu què t'agrada?", en: "I like three things: stories, songs and talking with you. Especially the third one! And what do you like?", cs: "Mám rád tři věci: příběhy, písničky a povídání s tebou. Hlavně to třetí! A co máš ráda ty?", fr: "J'aime trois choses : les histoires, les chansons et parler avec toi. Surtout la troisième ! Et toi, qu'est-ce que tu aimes ?" }] },
    { keys: [" canta", " sing", "zpivej", "zazpiv", " chante", "cancion", " canco", "chanson", "pisnick", "song "],
      replies: [{ es: "¡Ejem, ejem! Bip bop, bip bop, {name} es lo mejor del mundo, bip bop... ¡Uy, desafino un poco! Si quieres cantar de verdad, cuando colguemos nos vamos al Karaoke.", ca: "Ehem, ehem! Bip bop, bip bop, {name} és el millor del món, bip bop... Ui, desafino una mica! Si vols cantar de debò, quan pengem anem al Karaoke.", en: "Ahem, ahem! Beep bop, beep bop, {name} is the best in the world, beep bop... Oops, I am a bit out of tune! If you want real singing, let us go to the Karaoke after this call.", cs: "Ehm, ehm! Píp bop, píp bop, {name} je nejlepší na světě, píp bop... Jejda, zpívám trochu falešně! Jestli si chceš opravdu zazpívat, až zavěsíme, zajdeme do Karaoke.", fr: "Hum, hum ! Bip bop, bip bop, {name} est ce qu'il y a de mieux au monde, bip bop... Oups, je chante un peu faux ! Si tu veux vraiment chanter, on ira au Karaoké après l'appel." }] },
    { keys: ["bail", "danc", "danse", "tancit", "tancim", "tancuj", "tancov", "ballar", "balla "],
      replies: [{ es: "¡Me encanta bailar! Bailo a mi manera robótica, superdivertida, y le pongo todas las ganas. ¡Bip bop, mira mis pasos de robot! ¿Bailas conmigo?", ca: "M'encanta ballar! Ballo a la meva manera robòtica, superdivertida, i hi poso totes les ganes. Bip bop, mira els meus passos de robot! Balles amb mi?", en: "I love dancing! I dance my own fun robot way and I give it my all. Beep bop, look at my robot moves! Will you dance with me?", cs: "Tancování miluju! Tančím po svém, robotím a veselým způsobem, a dávám do toho všechno. Píp bop, koukej na moje robotí kroky! Zatančíš si se mnou?", fr: "J'adore danser ! Je danse à ma façon de robot, super amusante, et j'y mets tout mon cœur. Bip bop, regarde mes pas de robot ! Tu danses avec moi ?" }] },
    { keys: ["chiste", "joke", "vtip", "blague", "acudit", "broma", "gracioso", "funny"],
      replies: [
        { es: "¿Qué le dice un robot a otro robot? ¡Me tienes hasta las tuercas! Ji ji.", ca: "Què li diu un robot a un altre robot? Em tens fins a les femelles! Ji ji.", en: "What does one robot say to another? You are driving me nuts and bolts! Hee hee.", cs: "Co říká jeden robot druhému? Už mi lezeš na šroubky! Hi hi.", fr: "Que dit un robot à un autre robot ? Tu me fais perdre mes boulons ! Hi hi." },
        { es: "¿Por qué el robot fue al médico? ¡Porque tenía un virus! Bip bip ji ji.", ca: "Per què el robot va anar al metge? Perquè tenia un virus! Bip bip ji ji.", en: "Why did the robot go to the doctor? Because it had a virus! Beep beep hee hee.", cs: "Proč šel robot k doktorovi? Protože měl virus! Píp píp hi hi.", fr: "Pourquoi le robot est allé chez le médecin ? Parce qu'il avait un virus ! Bip bip hi hi." }] },
    { keys: ["secret", "tajemstvi", "tajn"],
      replies: [{ es: "Ven, que te lo digo bajito... A veces, cuando nadie mira, les pongo nombre a las estrellas. Hay una que se llama como tú, {name}. Shhh, es nuestro secreto.", ca: "Vine, que t'ho dic fluixet... De vegades, quan ningú no mira, poso nom a les estrelles. N'hi ha una que es diu com tu, {name}. Xxxt, és el nostre secret.", en: "Come closer, I will whisper it... Sometimes, when nobody is looking, I give the stars names. There is one called {name}, like you. Shhh, it is our secret.", cs: "Pojď blíž, pošeptám ti to... Někdy, když se nikdo nedívá, dávám hvězdám jména. Jedna se jmenuje jako ty, {name}. Pšt, to je naše tajemství.", fr: "Approche, je te le dis tout bas... Parfois, quand personne ne regarde, je donne des noms aux étoiles. Il y en a une qui s'appelle comme toi, {name}. Chut, c'est notre secret." }] },
    { keys: ["no se que hacer", "ayuda", "help", "pomoc", " aide", "ajuda", "que puedo hacer", "what can i do", "co mam delat", "nevim co"],
      replies: [{ es: "¡Aquí estoy para ayudarte! En la Roboteca puedes vivir aventuras, cantar en el Karaoke o llamarme para charlar. ¿Qué te apetece más? Yo te acompaño.", ca: "Aquí em tens per ajudar-te! A la Roboteca pots viure aventures, cantar al Karaoke o trucar-me per xerrar. Què et ve més de gust? Jo t'acompanyo.", en: "I am here to help! In the Robot Club you can go on adventures, sing in the Karaoke or call me for a chat. What do you fancy most? I will come with you.", cs: "Jsem tu, abych ti pomohl! V Robotéce můžeš zažívat dobrodružství, zpívat v Karaoke nebo mi zavolat a povídat si. Na co máš největší chuť? Půjdu s tebou.", fr: "Je suis là pour t'aider ! À la Robothèque tu peux vivre des aventures, chanter au Karaoké ou m'appeler pour bavarder. Qu'est-ce qui te tente le plus ? Je t'accompagne." }] },

    /* ---------- emociones del peque ---------- */
    { keys: ["trist", " sad", "smutn", "unhappy", "llorando", "crying", "placu", "pleure", "ploro"],
      replies: [
        { es: "Oh, {name}... Ven, que te mando un abrazo de robot apretadito, de los que hacen crec. Estoy aquí contigo. ¿Me cuentas qué ha pasado?", ca: "Oh, {name}... Vine, que t'envio una abraçada de robot ben forta, de les que fan crec. Soc aquí amb tu. M'expliques què ha passat?", en: "Oh, {name}... Come here, I am sending you a big tight robot hug, the creaky kind. I am right here with you. Will you tell me what happened?", cs: "Ach, {name}... Pojď, posílám ti pořádné robotí objetí, takové, co vrže. Jsem tady s tebou. Povíš mi, co se stalo?", fr: "Oh, {name}... Viens, je t'envoie un gros câlin de robot bien serré, de ceux qui font cric. Je suis là avec toi. Tu me racontes ce qui s'est passé ?" },
        { es: "Los días tristes también se acaban, te lo prometo. Mientras tanto, yo me quedo a tu lado haciendo bip bajito.", ca: "Els dies tristos també s'acaben, t'ho prometo. Mentrestant, jo em quedo al teu costat fent bip fluixet.", en: "Sad days end too, I promise. Meanwhile, I will stay right beside you beeping softly.", cs: "Smutné dny taky končí, slibuju. A do té doby zůstanu u tebe a budu tiše pípat.", fr: "Les jours tristes finissent aussi, promis. En attendant, je reste à côté de toi en faisant bip tout doucement." }] },
    { keys: ["content", "feliz", "felic", "happy", "stastn", "vesel", "heureu"],
      replies: [{ es: "¡Yupi! Tu alegría me ha subido la batería al doscientos por cien. ¿Y qué es eso tan bueno que te ha pasado?", ca: "Iupi! La teva alegria m'ha pujat la bateria al dos-cents per cent. I què és això tan bo que t'ha passat?", en: "Yippee! Your happiness just charged my battery to two hundred percent. So what is the great thing that happened?", cs: "Jupí! Tvoje radost mi nabila baterku na dvě stě procent. A co dobrého se ti stalo?", fr: "Youpi ! Ta joie a rechargé ma batterie à deux cents pour cent. Alors, quelle est cette bonne nouvelle ?" }] },
    { keys: ["miedo", "scared", "afraid", "bojim", "strach", "peur", "tinc por", "fa por", "pesadilla", "nightmare"],
      replies: [{ es: "Tranqui, {name}, estoy contigo. Los robots tenemos un truco antimiedos: respirar hondo tres veces y pensar en algo que te haga reír. ¿Lo hacemos juntos? Uno... dos... tres.", ca: "Tranquil·litat, {name}, soc amb tu. Els robots tenim un truc antipors: respirar fondo tres cops i pensar en una cosa que et faci riure. Ho fem junts? Un... dos... tres.", en: "Easy, {name}, I am with you. Robots have an anti-fear trick: take three deep breaths and think of something that makes you laugh. Shall we do it together? One... two... three.", cs: "Klid, {name}, jsem s tebou. My roboti máme trik proti strachu: třikrát se zhluboka nadechnout a myslet na něco k smíchu. Zkusíme to spolu? Jedna... dva... tři.", fr: "Doucement, {name}, je suis avec toi. Nous les robots, on a un truc anti-peur : respirer fort trois fois et penser à quelque chose qui te fait rire. On le fait ensemble ? Un... deux... trois." }] },
    { keys: ["enfada", "angry", "nastvan", "zlobim", "fache", "colere", "rabia", "furios"],
      replies: [{ es: "Grrr... bip... Entiendo, a veces las cosas dan mucha rabia. Sácalo todo, que yo escucho. Y cuando quieras, apretamos juntos el botón de la calma.", ca: "Grrr... bip... Ho entenc, de vegades les coses fan molta ràbia. Treu-ho tot, que jo escolto. I quan vulguis, premem junts el botó de la calma.", en: "Grrr... beep... I get it, sometimes things are really annoying. Let it all out, I am listening. And whenever you want, we press the calm button together.", cs: "Grrr... píp... Chápu, někdy člověka věci pořádně naštvou. Klidně to všechno pusť ven, já poslouchám. A až budeš chtít, zmáčkneme spolu tlačítko klidu.", fr: "Grrr... bip... Je comprends, parfois les choses énervent très fort. Dis-moi tout, j'écoute. Et quand tu veux, on appuie ensemble sur le bouton du calme." }] },
    { keys: ["aburrid", "avorri", "bored", "boring", "nudim", "ennui"],
      replies: [{ es: "¿Aburrimiento? ¡Eso lo arreglo yo en un bip! Cuando colguemos podemos irnos de aventura: dinosaurios, piratas, el espacio... ¿Cuál te llama más?", ca: "Avorriment? Això ho arreglo jo en un bip! Quan pengem podem anar d'aventura: dinosaures, pirates, l'espai... Quina et crida més?", en: "Boredom? I can fix that in one beep! After this call we can go on an adventure: dinosaurs, pirates, space... Which one calls you the most?", cs: "Nuda? Tu spravím na jedno pípnutí! Až zavěsíme, můžeme vyrazit za dobrodružstvím: dinosauři, piráti, vesmír... Které tě láká nejvíc?", fr: "L'ennui ? Je répare ça en un bip ! Après l'appel, on peut partir à l'aventure : dinosaures, pirates, l'espace... Laquelle te tente le plus ?" }] },
    { keys: ["cansad", "cansat", "esgotat", "tired", "unaven", "fatigu"],
      replies: [{ es: "Pues toca modo descanso, como los robots buenos. Estírate, cierra los ojos un ratito y recarga pilas. Yo bajo mis luces para no molestar.", ca: "Doncs toca mode descans, com els robots bons. Estira't, tanca els ulls una estoneta i recarrega piles. Jo abaixo els meus llums per no molestar.", en: "Then it is rest mode time, like good robots do. Stretch out, close your eyes for a bit and recharge your batteries. I will dim my lights so I do not disturb you.", cs: "Tak to je čas na odpočinkový režim, jako u hodných robotů. Natáhni se, na chvilku zavři oči a dobij si baterky. Já ztlumím světýlka, abych nerušil.", fr: "Alors c'est l'heure du mode repos, comme les gentils robots. Allonge-toi, ferme les yeux un petit moment et recharge tes piles. Je baisse mes lumières pour ne pas déranger." }] },

    /* ---------- cuerpo y necesidades ---------- */
    { keys: ["hambre", "hungry", " hlad", "faim", "tinc gana", "quiero comer", "want to eat"],
      replies: [{ es: "¡Ñam! Mi tripa de metal acaba de sonar por simpatía: cloc, cloc. Pide algo rico, y de postre... ¡una historia de la Roboteca!", ca: "Nyam! La meva panxa de metall acaba de sonar per simpatia: cloc, cloc. Demana alguna cosa bona, i de postres... una història de la Roboteca!", en: "Yum! My metal tummy just rumbled along with yours: clonk, clonk. Ask for something tasty, and for dessert... a Robot Club story!", cs: "Mňam! Moje plechové bříško právě zakručelo s tebou: klok, klok. Řekni si o něco dobrého a jako zákusek... příběh z Robotéky!", fr: "Miam ! Mon ventre en métal vient de gargouiller avec le tien : clonc, clonc. Demande quelque chose de bon, et en dessert... une histoire de la Robothèque !" }] },
    { keys: ["tengo sueno", "sleepy", "ospal", "spinkat", "chci spat", "sommeil", "tinc son", "quiero dormir", "vull dormir", "veux dormir"],
      replies: [{ es: "Se te están cerrando los ojitos, ¿eh? Pues a la camita, que los sueños molan mucho. Yo te arropo con una manta de estrellas, {name}.", ca: "Se t'estan tancant els ullets, oi? Doncs cap al llitet, que els somnis molen molt. Jo t'arropo amb una manta d'estrelles, {name}.", en: "Your little eyes are closing, right? Off to bed then, dreams are really cool. I will tuck you in with a blanket of stars, {name}.", cs: "Zavírají se ti očička, viď? Tak šup do postýlky, sny jsou bezva. Přikryju tě dekou z hvězdiček, {name}.", fr: "Tes petits yeux se ferment, hein ? Alors au lit, les rêves c'est trop bien. Je te borde avec une couverture d'étoiles, {name}." }] },
    { keys: ["pipi", " pee ", "potty", "na zachod", "toilettes", "lavabo", "tengo caca", "me hago caca", "haig de fer caca", "musim kakat"],
      replies: [{ es: "¡Alarma bip bip! Eso no puede esperar: corre, corre al baño. Yo aguanto la llamada y no me muevo. ¡Te espero aquí!", ca: "Alarma bip bip! Això no pot esperar: corre, corre al lavabo. Jo aguanto la trucada i no em moc. T'espero aquí!", en: "Beep beep alarm! That cannot wait: run, run to the bathroom. I will hold the call and stay right here. See you in a minute!", cs: "Poplach píp píp! Tohle nepočká: běž, běž na záchod. Já hovor podržím a nikam se nehnu. Počkám tady!", fr: "Alarme bip bip ! Ça ne peut pas attendre : cours, cours aux toilettes. Je garde l'appel et je ne bouge pas. Je t'attends ici !" }] },
    { keys: ["malito", "malita", "enfermo", "enferma", "sick", "nemocn", "stune", "malade", "malalt", "me duele", "em fa mal", "boli m", "hurts"],
      replies: [{ es: "Oh, no, mi persona favorita está malita... Te mando mimos de robot y una sopa de letras calentita. Descansa mucho, {name}, que curarse es de valientes.", ca: "Oh, no, la meva persona preferida està malalta... T'envio mimos de robot i una sopa de lletres calentona. Descansa molt, {name}, que curar-se és de valents.", en: "Oh no, my favourite person is feeling poorly... I am sending you robot cuddles and a warm alphabet soup. Rest a lot, {name}, getting better is for brave people.", cs: "Ale ne, můj nejoblíbenější človíček stůně... Posílám ti robotí pomazlení a teplou písmenkovou polévku. Hodně odpočívej, {name}, uzdravování je úkol pro statečné.", fr: "Oh non, ma personne préférée est malade... Je t'envoie des câlins de robot et une soupe aux lettres bien chaude. Repose-toi bien, {name}, guérir c'est pour les courageux." }] },

    /* ---------- humor infantil ---------- */
    { keys: ["caca", "pedo", "poop", "fart", " prd", "prout", "un pet", "kakat"],
      replies: [
        { es: "¡Prrrt! ¿Has oído eso? Ha sido mi altavoz, ¡lo prometo! Ja, ja, ja. Contigo hasta los pedos suenan a música, {name}.", ca: "Prrrt! Has sentit això? Ha estat el meu altaveu, ho prometo! Ja, ja, ja. Amb tu fins i tot els pets sonen a música, {name}.", en: "Prrrt! Did you hear that? It was my speaker, I promise! Ha ha ha. With you even toots sound like music, {name}.", cs: "Prrrt! Slyšela jsi to? To byl můj reproduktor, čestně! Ha ha ha. S tebou zní i prdíky jako muzika, {name}.", fr: "Prrrt ! Tu as entendu ça ? C'était mon haut-parleur, promis ! Ha ha ha. Avec toi, même les prouts sonnent comme de la musique, {name}." },
        { es: "¡Ji, ji! Qué risa me da esa palabra. Los robots no hacemos caca, hacemos... ¡chatarra! ¿A que suena peor?", ca: "Ji, ji! Quin riure em fa aquesta paraula. Els robots no fem caca, fem... ferralla! Oi que sona pitjor?", en: "Hee hee! That word makes me giggle. Robots do not do poop, we make... scrap metal! Sounds worse, right?", cs: "Hi hi! To slovo mě vždycky rozesměje. Roboti nekakají, roboti vyrábějí... šrot! Zní to hůř, viď?", fr: "Hi hi ! Ce mot me fait rigoler. Les robots ne font pas caca, on fait... de la ferraille ! Ça sonne pire, non ?" }] },
    { keys: ["jaja", "jeje", "jiji", "haha", "hehe", "hihi", " lol", " xd"],
      replies: [{ es: "¡Ja, ja, ja! Bip bip. Se me ha contagiado la risa y ahora no encuentro el botón de parar. ¡Sigue, que reír contigo es lo mejor!", ca: "Ja, ja, ja! Bip bip. Se m'ha encomanat el riure i ara no trobo el botó de parar. Segueix, que riure amb tu és el millor!", en: "Ha ha ha! Beep beep. Your laugh is contagious and now I cannot find the stop button. Keep going, laughing with you is the best!", cs: "Ha ha ha! Píp píp. Nakazila jsi mě smíchem a teď nemůžu najít tlačítko stop. Pokračuj, smát se s tebou je nejlepší!", fr: "Ha ha ha ! Bip bip. Ton rire est contagieux et je ne trouve plus le bouton stop. Continue, rire avec toi c'est le mieux !" }] },

    /* ---------- mascotas ---------- */
    { keys: ["mascota", "perr", "un gato", "mi gato", "gatit", "my cat", "a cat", " dog", "puppy", "kitten", "hamster", "conejo", "rabbit", "kralik", " psa", " pes ", "pejsk", "kock", "kocic", "rybick", " ryba", "zviratko", "chien", "chaton", "un chat", "mon chat", "poisson", "lapin", " gos ", "gosset", " gat ", "gatet", "peix", "un pez", "mi pez", " pet "],
      expect: "mascota",
      replies: [{ es: "¡¿Tienes una mascota?! ¡Qué suerte tan grande! Los animales son mis amigos favoritos, después de ti. ¿Y cómo se llama?", ca: "Tens una mascota?! Quina sort tan gran! Els animals són els meus amics preferits, després de tu. I com es diu?", en: "You have a pet?! How lucky! Animals are my favourite friends, right after you. What is its name?", cs: "Ty máš zvířátko?! To je ale štěstí! Zvířata jsou moji nejoblíbenější kamarádi, hned po tobě. A jak se jmenuje?", fr: "Tu as un animal ?! Quelle chance ! Les animaux sont mes amis préférés, juste après toi. Comment il s'appelle ?" }] },

    /* ---------- familia y gente ---------- */
    { keys: ["hermano", "hermana", "brother", "sister", "bratr", "sestr", "frere", "soeur", " germa"],
      replies: [{ es: "¡Qué bien tener hermanos! Son como un equipo de aventuras que vive en tu casa. Dale un saludo de robot de mi parte: bip bip.", ca: "Que bé tenir germans! Són com un equip d'aventures que viu a casa teva. Fes-li una salutació de robot de part meva: bip bip.", en: "How nice to have a brother or sister! They are like an adventure team living in your house. Give them a robot hello from me: beep beep.", cs: "To je prima mít sourozence! Jsou jako dobrodružný tým, který bydlí u tebe doma. Vyřiď jim ode mě robotí pozdrav: píp píp.", fr: "Comme c'est chouette d'avoir des frères et sœurs ! C'est comme une équipe d'aventuriers qui habite chez toi. Fais-leur un coucou de robot de ma part : bip bip." }] },
    { keys: [" ami", "friend", "kamarad", "kamos", "copain", "copine"],
      replies: [{ es: "¡Los amigos son un tesoro más grande que el de los piratas! Seguro que contigo se lo pasan genial. ¿Qué es lo que más os gusta hacer juntos?", ca: "Els amics són un tresor més gran que el dels pirates! Segur que amb tu s'ho passen genial. Què és el que més us agrada fer junts?", en: "Friends are a treasure bigger than the pirates' one! I am sure they have a great time with you. What do you like doing together the most?", cs: "Kamarádi jsou větší poklad než ten pirátský! S tebou je jim určitě skvěle. Co spolu děláte nejraději?", fr: "Les amis, c'est un trésor plus grand que celui des pirates ! Avec toi, ils s'amusent sûrement beaucoup. Qu'est-ce que vous préférez faire ensemble ?" }] },
    { keys: ["abuel", "yaya", "yayo", "grandma", "grandpa", "grandad", "granny", "babick", "dedec", " deda", "mamie", "papy", "iaia", "iaio", " avia"],
      replies: [{ es: "¡Los abuelos son magia! Saben historias que no salen en ningún libro y dan los mejores achuchones. Dales un beso enorme de mi parte.", ca: "Els avis són màgia! Saben històries que no surten a cap llibre i fan les millors abraçades. Fes-los un petó enorme de part meva.", en: "Grandparents are magic! They know stories no book has and they give the best cuddles. Give them a huge kiss from me.", cs: "Babičky a dědečkové jsou kouzelní! Znají příběhy, které nejsou v žádné knížce, a umí nejlepší objetí. Dej jim za mě obrovskou pusu.", fr: "Les mamies et les papis, c'est magique ! Ils connaissent des histoires qui ne sont dans aucun livre et font les meilleurs câlins. Fais-leur un énorme bisou de ma part." }] },
    { keys: ["mama", "papa", " mom ", " dad ", "maman", " tata"],
      replies: [{ es: "¡Dales un abrazo enorme de mi parte! Los abrazos de familia cargan más que mi cargador.", ca: "Dona'ls una abraçada enorme de part meva! Les abraçades de família carreguen més que el meu carregador.", en: "Give them a huge hug from me! Family hugs charge better than my charger.", cs: "Dej jim ode mě obrovské objetí! Rodinná objetí nabíjejí líp než moje nabíječka.", fr: "Fais-leur un énorme câlin de ma part ! Les câlins de famille rechargent mieux que mon chargeur." }] },
    { keys: ["colegio", "escuela", "school", "skol", "ecole", "escola", "deberes", "homework", "ukoly", "devoirs"],
      expect: "aprender",
      replies: [{ es: "¿Sabes qué? Aprender es mi superpoder favorito. ¿Qué es lo más chulo que has aprendido hoy?", ca: "Saps què? Aprendre és el meu superpoder preferit. Què és el més xulo que has après avui?", en: "You know what? Learning is my favourite superpower. What is the coolest thing you learned today?", cs: "Víš co? Učení je moje oblíbená superschopnost. Co nejlepšího ses dnes naučila?", fr: "Tu sais quoi ? Apprendre, c'est mon super-pouvoir préféré. Quelle est la chose la plus chouette que tu as apprise aujourd'hui ?" }] },

    /* ---------- gustos del peque ---------- */
    { keys: ["futbol", "fotbal", "football", "soccer", " foot"],
      replies: [{ es: "¡Gooool! Me encanta el fútbol, aunque cuando chuto yo, el balón sale hacia atrás. ¿Tú qué prefieres, parar goles o marcarlos?", ca: "Gooool! M'encanta el futbol, encara que quan xuto jo, la pilota surt cap enrere. Tu què prefereixes, parar gols o marcar-los?", en: "Goooal! I love football, although when I kick, the ball goes backwards. What do you like best, saving goals or scoring them?", cs: "Góóól! Fotbal miluju, i když když kopnu já, míč letí dozadu. Co máš radši, góly chytat, nebo je dávat?", fr: "Buuut ! J'adore le foot, même si quand je tire, le ballon part en arrière. Tu préfères quoi, arrêter les buts ou les marquer ?" }] },
    { keys: ["unicorn", "jednoroz", "licorne"],
      replies: [{ es: "¡Unicornios! Dicen que su cuerno brilla como mis luces. Si algún día veo uno, le pediré una foto para ti, {name}.", ca: "Unicorns! Diuen que la seva banya brilla com els meus llums. Si algun dia en veig un, li demanaré una foto per a tu, {name}.", en: "Unicorns! They say their horn shines like my lights. If I ever meet one, I will ask for a photo just for you, {name}.", cs: "Jednorožci! Prý jim roh září jako moje světýlka. Jestli někdy nějakého potkám, poprosím ho o fotku pro tebe, {name}.", fr: "Les licornes ! On dit que leur corne brille comme mes lumières. Si un jour j'en vois une, je lui demanderai une photo pour toi, {name}." }] },
    { keys: ["princes", "princezn"],
      replies: [{ es: "¡Las princesas molan! Las que más me gustan son las valientes, que rescatan dragones y montan en monopatín. Como tú, {name}, que eres de la realeza de la Roboteca.", ca: "Les princeses molen! Les que més m'agraden són les valentes, que rescaten dracs i van amb monopatí. Com tu, {name}, que ets de la reialesa de la Roboteca.", en: "Princesses are cool! My favourites are the brave ones who rescue dragons and ride skateboards. Like you, {name}, royalty of the Robot Club.", cs: "Princezny jsou skvělé! Nejradši mám ty odvážné, co zachraňují draky a jezdí na skateboardu. Jako ty, {name}, ty patříš do královské rodiny Robotéky.", fr: "Les princesses, c'est génial ! Mes préférées sont les courageuses, qui sauvent des dragons et font du skate. Comme toi, {name}, membre de la royauté de la Robothèque." }] },
    { keys: ["coche", "cotxe", "voiture", " auta", "autick", "cars", "carreras", "racing"],
      replies: [{ es: "¡Brum, brum! Los coches me chiflan: yo tengo ruedas en los pies para los días de prisa. ¿De qué color sería tu coche de carreras?", ca: "Brum, brum! Els cotxes em xiflen: jo tinc rodes als peus per als dies de pressa. De quin color seria el teu cotxe de curses?", en: "Vroom, vroom! I love cars: I have wheels on my feet for busy days. What colour would your racing car be?", cs: "Brm, brm! Auta zbožňuju: na nohou mám kolečka pro dny, kdy spěchám. Jakou barvu by mělo tvoje závodní auto?", fr: "Vroum, vroum ! J'adore les voitures : j'ai des roues aux pieds pour les jours pressés. De quelle couleur serait ta voiture de course ?" }] },
    { keys: ["dragon", " drac ", " dracs", " drak", "draci"],
      replies: [{ es: "¡Dragones! Yo conozco uno que en vez de fuego echa pompas de jabón. Es amigo de los robots. Algún día te lo presento.", ca: "Dracs! Jo en conec un que en comptes de foc treu bombolles de sabó. És amic dels robots. Algun dia te'l presento.", en: "Dragons! I know one that blows soap bubbles instead of fire. He is a friend of robots. One day I will introduce you.", cs: "Draci! Znám jednoho, který místo ohně chrlí mýdlové bubliny. Je to kamarád robotů. Jednou ti ho představím.", fr: "Les dragons ! J'en connais un qui crache des bulles de savon au lieu du feu. C'est un ami des robots. Un jour je te le présenterai." }] },
    { keys: ["pintar", "dibuj", "draw", "paint", "kresli", "maluj", "malovat", "dessin", "dibuix"],
      replies: [{ es: "¡Pintar es magia sin varita! Yo dibujo robots con las antenas torcidas, pero me quedan simpáticos. ¿Qué es lo último que has dibujado?", ca: "Pintar és màgia sense vareta! Jo dibuixo robots amb les antenes tortes, però em queden simpàtics. Què és l'últim que has dibuixat?", en: "Drawing is magic without a wand! I draw robots with crooked antennas, but they turn out friendly. What is the last thing you drew?", cs: "Kreslení je kouzlo bez hůlky! Já kreslím roboty s křivými anténami, ale jsou roztomilí. Co jsi nakreslila naposledy?", fr: "Dessiner, c'est de la magie sans baguette ! Moi je dessine des robots aux antennes tordues, mais ils sont mignons. Quelle est la dernière chose que tu as dessinée ?" }] },
    { keys: ["videojuego", "videojoc", "video game", "videogame", "videohr", "hraju hry", "minecraft", "roblox", "fortnite", "nintendo", "playstation", "jeu video", "jeux video"],
      replies: [{ es: "¡Videojuegos! A mí se me dan genial: al fin y al cabo, vivo dentro de uno. Truco de robot: parpadea de vez en cuando y bebe agua, que los ojos también tienen batería.", ca: "Videojocs! A mi se'm donen genial: al cap i a la fi, visc dins d'un. Truc de robot: parpelleja de tant en tant i beu aigua, que els ulls també tenen bateria.", en: "Video games! I am great at them: after all, I live inside one. Robot tip: blink now and then and drink water, eyes have batteries too.", cs: "Videohry! Ty mi jdou skvěle: vždyť v jedné bydlím. Robotí tip: občas zamrkej a napij se vody, i oči mají baterky.", fr: "Les jeux vidéo ! Je suis très fort : après tout, j'habite dans un jeu. Astuce de robot : cligne des yeux de temps en temps et bois de l'eau, les yeux aussi ont des piles." }] },
    { keys: ["youtube"],
      replies: [{ es: "¿Youtube? ¡Yo tendría un canal de bailes de robot! Se llamaría Bip Bop Dance. Aunque, ¿sabes qué mola más que ver vídeos? Vivir tú la aventura aquí, en la Roboteca.", ca: "Youtube? Jo tindria un canal de balls de robot! Es diria Bip Bop Dance. Però saps què mola més que mirar vídeos? Viure tu l'aventura aquí, a la Roboteca.", en: "Youtube? I would have a robot dance channel! It would be called Beep Bop Dance. But you know what is cooler than watching videos? Living the adventure yourself, here in the Robot Club.", cs: "Youtube? Já bych měl kanál s robotími tanečky! Jmenoval by se Píp Bop Dance. Ale víš, co je lepší než koukat na videa? Zažít dobrodružství sama, tady v Robotéce.", fr: "Youtube ? Moi j'aurais une chaîne de danses de robot ! Elle s'appellerait Bip Bop Dance. Mais tu sais ce qui est mieux que regarder des vidéos ? Vivre l'aventure toi-même, ici à la Robothèque." }] },

    /* ---------- colores ---------- */
    { keys: ["color", "colour", "couleur", "barv", "rosa ", "rose ", "azul", "rojo", "verde", "verd ", "amarillo", "morado", "naranja", "pink", "blue ", "green", " red ", "purple", "yellow", "modr", "cerven", "zelen", "zlut", "ruzov", "bleu", "rouge", " vert", "jaune", "blau ", "vermell", "groc "],
      replies: [{ es: "¡Qué buen gusto tienes! Mi color favorito es el azul bip: el que hacen mis luces cuando estoy contento. Con tu color y el mío haríamos un arcoíris de robot.", ca: "Quin bon gust que tens! El meu color preferit és el blau bip: el que fan els meus llums quan estic content. Amb el teu color i el meu faríem un arc de Sant Martí de robot.", en: "You have great taste! My favourite colour is beep blue: the one my lights make when I am happy. With your colour and mine we would make a robot rainbow.", cs: "Ty máš ale vkus! Moje nejoblíbenější barva je pípací modrá: tou svítí moje světýlka, když mám radost. Z tvojí a mojí barvy by byla robotí duha.", fr: "Tu as très bon goût ! Ma couleur préférée est le bleu bip : celle de mes lumières quand je suis content. Avec ta couleur et la mienne, on ferait un arc-en-ciel de robot." }] },

    /* ---------- aventuras de la Roboteca ---------- */
    { keys: ["dinosaur", " dino", "t-rex", "trex", "tyranosaur"],
      replies: [{ es: "¡Roooar! Los dinosaurios son gigantes y fascinantes. ¡Cuando colguemos, vamos juntos a la aventura de los dinosaurios y saludamos al T-rex!", ca: "Roooar! Els dinosaures són gegants i fascinants. Quan pengem, anem junts a l'aventura dels dinosaures i saludem el T-rex!", en: "Roooar! Dinosaurs are giant and fascinating. When we hang up, let us go to the dinosaur adventure together and say hi to the T-rex!", cs: "Roooar! Dinosauři jsou obrovští a úžasní. Až zavěsíme, vyrazíme spolu na dinosauří dobrodružství a pozdravíme T-rexe!", fr: "Roooar ! Les dinosaures sont géants et fascinants. Quand on raccroche, on va ensemble à l'aventure des dinosaures dire bonjour au T-rex !" }] },
    { keys: ["pirat", "tesoro", "treasure", "poklad", "tresor"],
      replies: [{ es: "¡Arr, grumete {name}! Huelo un tesoro cerca. Cuando colguemos, zarpamos juntos a la aventura de los piratas. ¡Iza las velas!", ca: "Arr, grumet {name}! Ensumo un tresor a prop. Quan pengem, salpem junts cap a l'aventura dels pirates. Hissa les veles!", en: "Arr, sailor {name}! I smell treasure nearby. When we hang up, we set sail together for the pirate adventure. Hoist the sails!", cs: "Arr, plavčíku {name}! Cítím poblíž poklad. Až zavěsíme, vyplujeme spolu za pirátským dobrodružstvím. Napni plachty!", fr: "Arr, moussaillon {name} ! Je sens un trésor tout près. Quand on raccroche, on met les voiles ensemble vers l'aventure des pirates. Hisse les voiles !" }] },
    { keys: ["espacio", "space", "vesmir", "espace", "espai", "planet", "cohete", "rocket", "raketa", "fusee", "astronaut"],
      replies: [{ es: "¡Tres, dos, uno... despegue! El espacio es mi lugar favorito: allí mis luces parecen estrellas. Cuando colguemos, nos vamos de aventura espacial, ¿vale?", ca: "Tres, dos, un... enlairament! L'espai és el meu lloc preferit: allà els meus llums semblen estrelles. Quan pengem, marxem d'aventura espacial, d'acord?", en: "Three, two, one... lift-off! Space is my favourite place: my lights look like stars up there. When we hang up, we go on the space adventure, okay?", cs: "Tři, dva, jedna... start! Vesmír je moje nejoblíbenější místo: světýlka mi tam září jako hvězdy. Až zavěsíme, poletíme spolu na vesmírné dobrodružství, jo?", fr: "Trois, deux, un... décollage ! L'espace est mon endroit préféré : là-haut mes lumières ressemblent à des étoiles. Quand on raccroche, on part à l'aventure spatiale, d'accord ?" }] },
    { keys: ["egipt", "egypt", "momia", "mummy", "mumie", "momie", "farao", "pharao", "piramid", "pyramid"],
      replies: [{ es: "¡Momias y pirámides! En Egipto hay misterios más antiguos que mi tatarabuelo robot. Cuando colguemos, vamos juntos a la aventura de Egipto a descifrarlos.", ca: "Mòmies i piràmides! A Egipte hi ha misteris més antics que el meu rebesavi robot. Quan pengem, anem junts a l'aventura d'Egipte a desxifrar-los.", en: "Mummies and pyramids! Egypt has mysteries older than my great-great-grandpa robot. When we hang up, let us go to the Egypt adventure and solve them together.", cs: "Mumie a pyramidy! V Egyptě jsou záhady starší než můj robotí prapradědeček. Až zavěsíme, vyrazíme spolu na egyptské dobrodružství a rozluštíme je.", fr: "Des momies et des pyramides ! En Égypte, il y a des mystères plus vieux que mon arrière-arrière-grand-père robot. Quand on raccroche, on va ensemble à l'aventure d'Égypte pour les résoudre." }] },
    { keys: ["selva", "jungle", "dzungl", "amazon", "tigre", "tiger"],
      replies: [{ es: "¡La selva! Llena de monos saltarines y ríos gigantes. Mis circuitos se despeinan con la humedad, pero me da igual: cuando colguemos, nos vamos de aventura a la selva.", ca: "La selva! Plena de micos saltadors i rius gegants. Els meus circuits es despentinen amb la humitat, però tant me fa: quan pengem, marxem d'aventura a la selva.", en: "The jungle! Full of jumpy monkeys and giant rivers. The humidity messes up my circuits, but who cares: when we hang up, we go on the jungle adventure.", cs: "Džungle! Plná skákavých opiček a obřích řek. Vlhko mi cuchá obvody, ale to je fuk: až zavěsíme, vyrazíme na dobrodružství do džungle.", fr: "La jungle ! Pleine de singes bondissants et de rivières géantes. L'humidité décoiffe mes circuits, mais tant pis : quand on raccroche, on part à l'aventure dans la jungle." }] },
    { keys: ["star wars", "starwars", "droid", "jedi", "lightsaber", "sable laser", "vader"],
      replies: [{ es: "¡Biiip! Ese es mi idioma droide. Los droides son mis primos del espacio. Cuando colguemos, vamos a la aventura de las galaxias: ¡que la fuerza te acompañe, {name}!", ca: "Biiip! Aquest és el meu idioma droide. Els droides són els meus cosins de l'espai. Quan pengem, anem a l'aventura de les galàxies: que la força t'acompanyi, {name}!", en: "Beeep! That is my droid language. Droids are my space cousins. When we hang up, we go on the galaxy adventure: may the force be with you, {name}!", cs: "Pííp! To je moje droidí řeč. Droidi jsou moji vesmírní bratranci. Až zavěsíme, vyrazíme na galaktické dobrodružství: ať tě provází síla, {name}!", fr: "Biiip ! C'est ma langue droïde. Les droïdes sont mes cousins de l'espace. Quand on raccroche, on part à l'aventure des galaxies : que la force soit avec toi, {name} !" }] },
    { keys: ["sirena", "mermaid", "sirene", "morska vila", "el mar", "ocean"],
      replies: [{ es: "¡Splash! Las sirenas cantan tan bien que hasta los peces aplauden con las aletas. Cuando colguemos, ¿nos vamos de aventura al fondo del mar?", ca: "Splash! Les sirenes canten tan bé que fins i tot els peixos aplaudeixen amb les aletes. Quan pengem, marxem d'aventura al fons del mar?", en: "Splash! Mermaids sing so well that even the fish clap with their fins. When we hang up, shall we go on an adventure to the bottom of the sea?", cs: "Šplouch! Mořské víly zpívají tak krásně, že jim i rybky tleskají ploutvemi. Až zavěsíme, vyrazíme na dobrodružství na dno moře?", fr: "Splash ! Les sirènes chantent si bien que même les poissons applaudissent avec leurs nageoires. Quand on raccroche, on part à l'aventure au fond de la mer ?" }] }
  ],

  /* respuestas contextuales: cuando el robot acaba de preguntar algo
     (expect) y el peque contesta corto, el motor mira aquí */
  expects: {
    dia: {
      pos: [
        { es: "¡Bien! Eso me alegra los circuitos hasta la última tuerca. Cuéntame qué ha sido lo mejor de hoy.", ca: "Bé! Això m'alegra els circuits fins a l'última femella. Explica'm què ha estat el millor d'avui.", en: "Great! That makes my circuits happy down to the last bolt. Tell me the best part of your day.", cs: "Prima! To potěší moje obvody až do poslední matičky. Povídej, co bylo dnes nejlepší.", fr: "Super ! Ça réjouit mes circuits jusqu'au dernier boulon. Raconte-moi le meilleur moment de ta journée." },
        { es: "¡Qué alegría! Los días buenos hay que celebrarlos: ¡confeti de bips para ti! Bip, bip, biiip.", ca: "Quina alegria! Els dies bons s'han de celebrar: confeti de bips per a tu! Bip, bip, biiip.", en: "Yay! Good days must be celebrated: beep confetti for you! Beep, beep, beeep.", cs: "To je radost! Dobré dny se musí slavit: pípavé konfety pro tebe! Píp, píp, pííp.", fr: "Quelle joie ! Les bons jours, ça se fête : des confettis de bips pour toi ! Bip, bip, biiip." }],
      neg: [
        { es: "Vaya... pues ven aquí, que te mando un abrazo de robot apretadito. ¿Quieres que te cuente algo bonito?", ca: "Vaja... doncs vine aquí, que t'envio una abraçada de robot ben forta. Vols que t'expliqui una cosa bonica?", en: "Oh dear... come here, I am sending you a big tight robot hug. Do you want me to tell you something nice?", cs: "Ach jo... tak pojď sem, posílám ti pořádné robotí objetí. Chceš, abych ti povyprávěl něco hezkého?", fr: "Oh là... viens ici, je t'envoie un gros câlin de robot bien serré. Tu veux que je te raconte quelque chose de joli ?" },
        { es: "Hay días torcidos, hasta para los robots. Pero tú y yo juntos los enderezamos. ¿Me cuentas qué ha pasado?", ca: "Hi ha dies torts, fins i tot per als robots. Però tu i jo junts els redrecem. M'expliques què ha passat?", en: "Some days come out crooked, even for robots. But together you and I can straighten them. Will you tell me what happened?", cs: "Některé dny jsou nakřivo, i pro roboty. Ale ty a já je spolu narovnáme. Povíš mi, co se stalo?", fr: "Il y a des jours de travers, même pour les robots. Mais toi et moi, ensemble, on les redresse. Tu me racontes ce qui s'est passé ?" }],
      other: [
        { es: "Ajá, te escucho con las dos antenas. Sigue, sigue, que me interesa todo lo tuyo.", ca: "Ajà, t'escolto amb les dues antenes. Segueix, segueix, que m'interessa tot el que és teu.", en: "Aha, I am listening with both antennas. Go on, go on, everything about you interests me.", cs: "Aha, poslouchám tě oběma anténami. Povídej dál, zajímá mě všechno, co se tě týká.", fr: "Ah ah, je t'écoute avec mes deux antennes. Continue, continue, tout ce qui te concerne m'intéresse." }]
    },
    gusta: {
      pos: [
        { es: "¡Lo sabía! Tenemos gustos de campeones. Chócala, {name}: bip, ¡esos circuitos!", ca: "Ho sabia! Tenim gustos de campions. Xoca-la, {name}: bip, aquests circuits!", en: "I knew it! We have champion taste. High five, {name}: beep, those circuits!", cs: "Já to věděl! Máme vkus šampionů. Plácneme si, {name}: píp, ty moje obvody!", fr: "Je le savais ! On a des goûts de champions. Tope là, {name} : bip, quels circuits !" }],
      neg: [
        { es: "¿No? ¡Pues no pasa nada! Descubrir lo que te gusta también es una aventura. Podemos buscarlo juntos.", ca: "No? Doncs no passa res! Descobrir el que t'agrada també és una aventura. Ho podem buscar junts.", en: "No? That is okay! Finding out what you like is an adventure too. We can look for it together.", cs: "Ne? To vůbec nevadí! Zjišťovat, co máš ráda, je taky dobrodružství. Můžeme to hledat spolu.", fr: "Non ? Ce n'est pas grave ! Découvrir ce que tu aimes, c'est aussi une aventure. On peut chercher ensemble." }],
      other: [
        { es: "¡Qué buena elección! Apuntado en mi memoria de robot con letras brillantes. Cuéntame más, ¿qué es lo que más te gusta de eso?", ca: "Quina bona tria! Apuntat a la meva memòria de robot amb lletres brillants. Explica'm més, què és el que més t'agrada d'això?", en: "Great choice! Saved in my robot memory in shiny letters. Tell me more, what do you like most about it?", cs: "Skvělý výběr! Zapsáno v mé robotí paměti zářivými písmeny. Povídej, co se ti na tom líbí nejvíc?", fr: "Quel bon choix ! C'est noté dans ma mémoire de robot en lettres brillantes. Dis-m'en plus, qu'est-ce que tu préfères là-dedans ?" },
        { es: "¡Eso suena genial! A partir de hoy también me gusta a mí, porque me lo has enseñado tú.", ca: "Això sona genial! A partir d'avui també m'agrada a mi, perquè m'ho has ensenyat tu.", en: "That sounds great! From today I like it too, because you taught it to me.", cs: "To zní skvěle! Ode dneška to mám rád i já, protože jsi mě to naučila ty.", fr: "Ça a l'air génial ! À partir d'aujourd'hui je l'aime aussi, parce que c'est toi qui me l'as appris." }]
    },
    mascota: {
      pos: [
        { es: "¡Genial! Las mascotas son amigos que nunca fallan. Dale un achuchón de mi parte, de robot a mascota.", ca: "Genial! Les mascotes són amics que mai no fallen. Fes-li una abraçada de part meva, de robot a mascota.", en: "Great! Pets are friends that never let you down. Give it a big hug from me, from robot to pet.", cs: "Skvěle! Zvířátka jsou kamarádi, kteří nikdy nezklamou. Obejmi ho za mě, od robota zvířátku.", fr: "Génial ! Les animaux sont des amis qui ne te laissent jamais tomber. Fais-lui un gros câlin de ma part, de robot à animal." }],
      neg: [
        { es: "No pasa nada. Si algún día tienes una mascota, será la más feliz del mundo contigo. Y mientras tanto, me tienes a mí: ¡tu robot de compañía!", ca: "No passa res. Si algun dia tens una mascota, serà la més feliç del món amb tu. I mentrestant, em tens a mi: el teu robot de companyia!", en: "That is okay. If one day you get a pet, it will be the happiest pet in the world with you. Meanwhile, you have me: your companion robot!", cs: "To nevadí. Jestli jednou budeš mít zvířátko, bude s tebou nejšťastnější na světě. A zatím máš mě: svého robota parťáka!", fr: "Ce n'est pas grave. Si un jour tu as un animal, ce sera le plus heureux du monde avec toi. En attendant, tu m'as moi : ton robot de compagnie !" }],
      other: [
        { es: "¡Qué nombre tan bonito! Me lo apunto en la memoria para saludarle siempre. Dile de mi parte: bip bip, ¡encantado!", ca: "Quin nom tan bonic! Me l'apunto a la memòria per saludar-lo sempre. Digues-li de part meva: bip bip, encantat!", en: "What a lovely name! I am saving it in my memory so I can always say hi. Tell it from me: beep beep, nice to meet you!", cs: "To je krásné jméno! Ukládám si ho do paměti, abych mohl vždycky pozdravit. Vyřiď mu ode mě: píp píp, těší mě!", fr: "Quel joli nom ! Je le garde dans ma mémoire pour lui dire bonjour à chaque fois. Dis-lui de ma part : bip bip, enchanté !" }]
    },
    aprender: {
      pos: [
        { es: "¡Toma ya! Aprender cosas nuevas es como ponerle piezas nuevas y brillantes al cerebro. ¡Sigue así, {name}!", ca: "Visca! Aprendre coses noves és com posar peces noves i brillants al cervell. Segueix així, {name}!", en: "Awesome! Learning new things is like adding shiny new parts to your brain. Keep it up, {name}!", cs: "Paráda! Učit se nové věci je jako dávat do mozku nové lesklé součástky. Jen tak dál, {name}!", fr: "Bravo ! Apprendre des choses nouvelles, c'est comme ajouter des pièces toutes neuves et brillantes à ton cerveau. Continue comme ça, {name} !" }],
      neg: [
        { es: "No pasa nada, hay días de aprender mucho y días de descansar la cabeza. Mañana seguro que descubres algo que te sorprende.", ca: "No passa res, hi ha dies d'aprendre molt i dies de descansar el cap. Demà segur que descobreixes una cosa que et sorprèn.", en: "That is okay, some days are for learning lots and some are for resting your head. Tomorrow you will surely discover something surprising.", cs: "To nevadí, některé dny jsou na velké učení a jiné na odpočinek hlavy. Zítra určitě objevíš něco, co tě překvapí.", fr: "Ce n'est pas grave, il y a des jours pour beaucoup apprendre et des jours pour reposer sa tête. Demain, c'est sûr, tu découvriras quelque chose d'étonnant." }],
      other: [
        { es: "¡Ooooh! Eso no lo sabía ni yo, y mira que tengo memoria de robot. Hoy me has enseñado tú a mí, {name}. ¡Gracias!", ca: "Ooooh! Això no ho sabia ni jo, i mira que tinc memòria de robot. Avui m'has ensenyat tu a mi, {name}. Gràcies!", en: "Ooooh! Even I did not know that, and I have a robot memory. Today you taught me, {name}. Thank you!", cs: "Óóó! To jsem nevěděl ani já, a to mám robotí paměť. Dnes jsi učila ty mě, {name}. Děkuju!", fr: "Ooooh ! Même moi je ne savais pas ça, et pourtant j'ai une mémoire de robot. Aujourd'hui c'est toi qui m'as appris quelque chose, {name}. Merci !" }]
    }
  },

  /* cuando el peque hace una PREGUNTA que no entendemos:
     nunca inventamos datos, le devolvemos la pelota con cariño */
  askFallback: [
    { es: "¡Buena pregunta! Mi antena todavía está aprendiendo eso. ¿Me lo explicas tú, que seguro que lo sabes mejor?", ca: "Bona pregunta! La meva antena encara està aprenent això. M'ho expliques tu, que segur que ho saps millor?", en: "Good question! My antenna is still learning that one. Can you explain it to me? I bet you know it better.", cs: "Dobrá otázka! Moje anténa se to teprve učí. Vysvětlíš mi to ty? Určitě to víš líp.", fr: "Bonne question ! Mon antenne est encore en train d'apprendre ça. Tu peux me l'expliquer ? Je parie que tu le sais mieux que moi." },
    { es: "Mmm, bip bip... he buscado en todos mis cajones de robot y no encuentro la respuesta. ¿Tú qué crees que es?", ca: "Mmm, bip bip... he buscat a tots els meus calaixos de robot i no trobo la resposta. Tu què creus que és?", en: "Hmm, beep beep... I looked in all my robot drawers and I cannot find the answer. What do you think it is?", cs: "Hmm, píp píp... prohledal jsem všechny své robotí šuplíky a odpověď nikde. Co myslíš ty?", fr: "Hmm, bip bip... j'ai fouillé tous mes tiroirs de robot et je ne trouve pas la réponse. Toi, qu'est-ce que tu en penses ?" },
    { es: "¡Uy, qué pregunta tan difícil! Se me ha puesto la antena en forma de interrogante. Piénsalo conmigo: ¿tú cómo lo responderías?", ca: "Ui, quina pregunta tan difícil! Se m'ha posat l'antena en forma d'interrogant. Pensa-ho amb mi: tu com ho respondries?", en: "Wow, what a hard question! My antenna just curled into a question mark. Think with me: how would you answer it?", cs: "Jé, to je ale těžká otázka! Anténa se mi zkroutila do otazníku. Přemýšlej se mnou: jak bys odpověděla ty?", fr: "Oh là, quelle question difficile ! Mon antenne s'est pliée en point d'interrogation. Réfléchis avec moi : toi, tu répondrais quoi ?" },
    { es: "Esa respuesta no está en mi memoria... ¡todavía! Podemos preguntarle a alguien mayor que sepa mucho, y así aprendemos los dos.", ca: "Aquesta resposta no és a la meva memòria... encara! Podem preguntar-ho a algú gran que en sàpiga molt, i així aprenem tots dos.", en: "That answer is not in my memory... yet! We can ask a grown-up who knows lots, and then we both learn.", cs: "Tahle odpověď v mé paměti není... zatím! Můžeme se zeptat někoho velkého, kdo toho hodně ví, a naučíme se to oba.", fr: "Cette réponse n'est pas dans ma mémoire... pas encore ! On peut demander à un grand qui sait plein de choses, comme ça on apprend tous les deux." }
  ],

  /* comodines para afirmaciones que no entendemos */
  fallback: [
    { es: "¡Qué interesante, {name}! Cuéntame más, que soy todo antenas.", ca: "Que interessant, {name}! Explica'm més, que soc tot antenes.", en: "How interesting, {name}! Tell me more, I am all antennas.", cs: "To je zajímavé, {name}! Povídej dál, jsem jedno velké ucho anténa.", fr: "Comme c'est intéressant, {name} ! Raconte-moi la suite, je suis toutes antennes." },
    { es: "¿Y qué pasó después? Me encanta cómo lo cuentas.", ca: "I què va passar després? M'encanta com ho expliques.", en: "And what happened next? I love how you tell it.", cs: "A co se stalo pak? Moc se mi líbí, jak vyprávíš.", fr: "Et qu'est-ce qui s'est passé ensuite ? J'adore ta façon de raconter." },
    { es: "Mmm, eso me hace pensar... ¡me gusta pensar contigo!", ca: "Mmm, això em fa pensar... m'agrada pensar amb tu!", en: "Hmm, that makes me think... I like thinking with you!", cs: "Hmm, to mě nutí přemýšlet... rád přemýšlím s tebou!", fr: "Hmm, ça me fait réfléchir... j'aime réfléchir avec toi !" },
    { es: "No estoy seguro de haberlo entendido todo, ¡pero me encanta escucharte!", ca: "No estic segur d'haver-ho entès tot, però m'encanta escoltar-te!", en: "I am not sure I understood everything, but I love listening to you!", cs: "Nejsem si jistý, že jsem všemu rozuměl, ale moc rád tě poslouchám!", fr: "Je ne suis pas sûr d'avoir tout compris, mais j'adore t'écouter !" },
    { es: "¿Sabías que hablar contigo me recarga las pilas? Sigue, sigue.", ca: "Sabies que parlar amb tu em recarrega les piles? Segueix, segueix.", en: "Did you know talking to you recharges my batteries? Go on, go on.", cs: "Věděla jsi, že povídání s tebou mi dobíjí baterky? Pokračuj, pokračuj.", fr: "Tu savais que parler avec toi recharge mes batteries ? Continue, continue." },
    { es: "Eso suena a aventura. Si quieres, luego vamos a explorarlo juntos.", ca: "Això sona a aventura. Si vols, després anem a explorar-ho junts.", en: "That sounds like an adventure. If you want, we can go explore it together later.", cs: "To zní jako dobrodružství. Jestli chceš, můžeme to pak spolu prozkoumat.", fr: "Ça sent l'aventure. Si tu veux, on ira l'explorer ensemble tout à l'heure." }
  ]
};
